# Example shown in the session for bind-mount with init container via Docker Compose
---
services:
  init-gateway:
    image: inductiveautomation/ignition:8.1.19
    entrypoint: sh -c
    volumes:
      # We mount this in the container as `/data` to not conflict with built-in files
      # at `/usr/local/bin/ignition/data`
      - ./gateway-data:/data
    command:
      # Seed the files from the image to our /data if marker file not present, skip
      # if the marker file exists (and implicitly exit cleanly with status code 0)
      - |
        if [ ! -f /data/.ignition-seed-complete ]; then
          touch /data/.ignition-seed-complete ;
          cp -dpR /usr/local/bin/ignition/data/* /data/ ;
        fi
  gateway:
    image: inductiveautomation/ignition:8.1.19
    ports:
      - 8488:8088
      - 8443:8043
    volumes:
      - ./gateway-data:/usr/local/bin/ignition/data
    environment:
      GATEWAY_ADMIN_PASSWORD: password
      ACCEPT_IGNITION_EULA: "Y"
      IGNITION_EDITION: standard
    # Use depends_on to only launch this container if our init container exits cleanly
    depends_on:
      init-gateway:
        condition: service_completed_successfully
    command: >
      -n dau_ind_upgrade_testing